Page Title: VMOCK | NetworkFeedbackPage

#Object Definitions
====================================================================================
dashboardPage				css				a[href="/dashboard/resume"]
verifyOnDashboardPage		xpath			//div[@class="card-title"]/span[text()="RE"]
networkFeedbackPage			css				div[aria-label="Network Feedback Product"]
requestNetworkFeedback		xpath			//a[text()="Request Feedback from your Network"]
selectResume				css				div[title="Amar_Gupta_Resume.pdf"]
nextButton					css				a[id="next-button-resume"]
addIndividallyReviewer		xpath			//div[@class="hr-text"][text()="Add Individually"]
enterName					css				input[placeholder="type name"]
enterEmail					css				input[placeholder="type email"]
addButton					css				button[aria-label="Click here to add individual reviewer"]
emailAdded					css				div[title="${option}"]
nextButtonReviewer			css				a[id="next-button-reviewer"]
writeTheMessage				xpath			//div[@class="card-heading"][text()="WRITE THE MESSAGE"]
jobPosition					css				input[aria-label="Type Job Position"]
additionalMessage			css				textarea[aria-label="Type Additional Message"]
requestToReviewer			css				a[aria-label="Click here to send request to reviewer"]
requestSent					xpath			//div[@class="nf-request-swal-title text-success"][text()="Request has been sent succesfully to : "]
okButton					css				button[class="confirm"]
addNadaInbox				xpath			//span[text()="Add Inbox"]
emailIdNada					css				input[class="user_name"]
selectEmail					css				select[id="domain"]
selectNadaEmail				css				option[value="nada.ltd"]
acceptButton				css				a[class="button success"]
openEmail					xpath			//div[text()="Requesting feedback on Resume"]
frameId						css				iframe[id="idIframe"]
giveFeedbackEmail			xpath			//a[text()="Give Feedback"]
buttonGiveFeedback			css				button[aria-label="Click here to give Gaurav your feedback"]
letStart					css				button[aria-label="Click to start giving your feedback"]
addNote						css				a[id="add-note-on-footer"]
titleFeedback				css				input[placeholder="Type the title"]
typeFeedback				css				textarea[placeholder="Type the feedback"]
finishNote					xpath			//button[@class="btn btn-primary"][text()="Finish"]