Page Title: VMOCK | ResumeUploadPage

#Object Definitions
====================================================================================
skipIntro						css			button[class="dashboard-intro-close"]
resumeUploadButton				xpath		//span[contains(text(),"Upload")]
uploadNewResume					css			img[src="/dist/img/upload-new-resume.png"]
resumeUploadedSuccessfully		xpath		//span[@class="noty_text"][text()="${text}"]
viewFeedback					xpath		//a[text()="View feedback"]
seeDetailedFeedback				xpath		//a[@aria-label="See Detailed Feedback"][text()="See Detailed Feedback"]
verifyImpactHeader				xpath		//div[@class="infobox-heading text-uppercase h5-div"][text()="${options}"]
imapctOptions					xpath 		//a[contains(text(),"${options}")]
seeGuidance						xpath		//button[@class="btn btn-outline-primary js-sf-button"][text()="see guidance"]					
modalHeader						xpath		//strong[text()="${options}"]
modalSubHeader					xpath		//div[@class="hr-text"][text()="${options}"]
exampleHeader					xpath		//a[@aria-label="EXAMPLES"][text()="EXAMPLES"]
closeButton						css			button[class="close-btn"][aria-label="click to close guidance."]
presentationPage				xpath		//a[contains(text(),"Presentation")]
competenciesPage				xpath 		//a[contains(text(),"Competencies")]
summaryPage						xpath		//a[contains(text(),"Summary")]
bulletLevelFeedbackPage			xpath		//a[contains(text(),"Bullet Level Feedback")]
skipBulletFTUE					css			div[class="enjoyhint_close_btn"]	
showBulletpage					xpath		//div[@class="bullet-feedback-filters-heading"][text()="Show Bullets"]
markedYellow					css			div[class="bullet-feedback-filter bullet-feedback-filter-warning "]
markedRed						css			div[class="bullet-feedback-filter bullet-feedback-filter-danger "]
textContains					xpath		//div[@class="bullet-feedback-viewer-checks-title"][text()="${option}"]
scoreCalculation				xpath		//a[text()="See how it is calculated"]
scoreBased						xpath		//div[text()="Your score is based on 3 core modules"]
closeScoreCalculation			css			button[class="close-btn"][tabindex="30"]
toggleButton					css			div[class="slider round"]
verifyToggleOff					xpath       //label[@class="presentation-toggle-text"][contains(text(),"Toggle")]
addToDictionary					xpath 		//a[text()="+ Add to Dictionary"]
dictionaryHeader				xpath		//h4[text()="Add to Dictionary"]
addCctcDictionary				xpath		//span[text()="cctc"]
addDictionary					xpath		//button[text()="Add to Dictionary"]
addedDictionary					xpath		//h4[text()="Previously Added Words"]
reuploadResume					xpath		//a[text()="Reupload Resume"][@data-radium="true"]
verifyResumeUploading			css			a[aria-label="VMock logo - Student dashboard"]
elementNotPresent				xpath		//span[@class="badge badge-keyword"][contains(text(),"CCTC")]

